# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(437, 333)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("formula-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(93, 131, 90, 24))
        self.label.setStyleSheet("QLabel{backgroung: rgb(255, 255, 127)}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(93, 162, 84, 24))
        self.label_2.setStyleSheet("QLabel{backgroung: rgb(255, 255, 127)}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 70, 171, 31))
        self.label_3.setStyleSheet("\n"
"QLabel{font: 10pt \"MS Shell Dlg 2\";}\n"
"")
        self.label_3.setObjectName("label_3")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 441, 321))
        self.listWidget.setStyleSheet("QListWidget{background:rgb(205, 238, 236)}")
        self.listWidget.setObjectName("listWidget")
        self.lineEditUsername = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUsername.setGeometry(QtCore.QRect(190, 131, 137, 22))
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.lineEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(190, 162, 137, 22))
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonRegister = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRegister.setGeometry(QtCore.QRect(111, 216, 93, 31))
        self.pushButtonRegister.setStyleSheet("QPushButton{background:rgb(170, 255, 255)}")
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.pushButtonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(214, 216, 93, 31))
        self.pushButtonLogin.setStyleSheet("QPushButton{background:rgb(170, 255, 255)}")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.listWidget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEditUsername.raise_()
        self.lineEditPassword.raise_()
        self.pushButtonRegister.raise_()
        self.pushButtonLogin.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login"))
        self.label.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Username</span></p></body></html>"))
        self.label_2.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Password</span></p></body></html>"))
        self.label_3.setText(_translate("LoginWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Authorization</span></p></body></html>"))
        self.pushButtonRegister.setText(_translate("LoginWindow", "Register"))
        self.pushButtonLogin.setText(_translate("LoginWindow", "Login"))
