# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'race.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchWindow(object):
    def setupUi(self, SearchWindow):
        SearchWindow.setObjectName("SearchWindow")
        SearchWindow.resize(785, 496)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("formula-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearchWindow.setWindowIcon(icon)
        SearchWindow.setAutoFillBackground(False)
        SearchWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(SearchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(150, 20, 481, 41))
        self.textEdit.setStyleSheet("QTextEdit { background: rgb(170, 255, 255)}")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.pushButtonReset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReset.setGeometry(QtCore.QRect(190, 427, 161, 41))
        self.pushButtonReset.setStyleSheet("QPushButton{background: rgb(255, 255, 127)}")
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.pushButtonSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSubmit.setGeometry(QtCore.QRect(450, 427, 141, 41))
        self.pushButtonSubmit.setStyleSheet("QPushButton{background: rgb(255, 255, 127)}")
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(191, 167, 256, 33))
        self.textEdit_5.setStyleSheet("QTextEdit { background:rgb(170, 255, 255)}")
        self.textEdit_5.setReadOnly(True)
        self.textEdit_5.setObjectName("textEdit_5")
        self.lineEditWin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWin.setGeometry(QtCore.QRect(454, 172, 137, 22))
        self.lineEditWin.setObjectName("lineEditWin")
        self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(191, 207, 256, 34))
        self.textEdit_7.setStyleSheet("QTextEdit { background:rgb(170, 255, 255)}")
        self.textEdit_7.setReadOnly(True)
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(191, 333, 256, 34))
        self.textEdit_6.setStyleSheet("QTextEdit { background:rgb(170, 255, 255)}")
        self.textEdit_6.setReadOnly(True)
        self.textEdit_6.setObjectName("textEdit_6")
        self.lineEditPodiums = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPodiums.setGeometry(QtCore.QRect(454, 339, 137, 22))
        self.lineEditPodiums.setObjectName("lineEditPodiums")
        self.lineEditPoints = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPoints.setGeometry(QtCore.QRect(454, 213, 137, 22))
        self.lineEditPoints.setObjectName("lineEditPoints")
        self.lineEditChampionship = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditChampionship.setGeometry(QtCore.QRect(454, 258, 137, 22))
        self.lineEditChampionship.setObjectName("lineEditChampionship")
        self.textEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_8.setGeometry(QtCore.QRect(191, 293, 256, 33))
        self.textEdit_8.setStyleSheet("QTextEdit { background:rgb(170, 255, 255)}")
        self.textEdit_8.setReadOnly(True)
        self.textEdit_8.setObjectName("textEdit_8")
        self.lineEditTeam = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTeam.setGeometry(QtCore.QRect(454, 128, 137, 22))
        self.lineEditTeam.setObjectName("lineEditTeam")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(191, 81, 256, 34))
        self.textEdit_2.setStyleSheet("QTextEdit { background:rgb(170, 255, 255)}")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEditName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditName.setGeometry(QtCore.QRect(454, 87, 137, 22))
        self.lineEditName.setObjectName("lineEditName")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(191, 122, 256, 34))
        self.textEdit_3.setStyleSheet("QTextEdit { background:rgb(170, 255, 255)}")
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.lineEditEntries = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditEntries.setGeometry(QtCore.QRect(454, 298, 137, 22))
        self.lineEditEntries.setObjectName("lineEditEntries")
        self.textEdit_9 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_9.setGeometry(QtCore.QRect(191, 252, 256, 34))
        self.textEdit_9.setStyleSheet("QTextEdit { background:rgb(170, 255, 255)}")
        self.textEdit_9.setReadOnly(True)
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_10.setGeometry(QtCore.QRect(191, 374, 256, 33))
        self.textEdit_10.setStyleSheet("QTextEdit { background:rgb(170, 255, 255)}")
        self.textEdit_10.setReadOnly(True)
        self.textEdit_10.setObjectName("textEdit_10")
        self.comboBoxNationality = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxNationality.setGeometry(QtCore.QRect(454, 379, 131, 22))
        self.comboBoxNationality.setObjectName("comboBoxNationality")
        SearchWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SearchWindow)
        self.statusbar.setObjectName("statusbar")
        SearchWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SearchWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchWindow)
        SearchWindow.setTabOrder(self.lineEditName, self.lineEditTeam)
        SearchWindow.setTabOrder(self.lineEditTeam, self.lineEditWin)
        SearchWindow.setTabOrder(self.lineEditWin, self.lineEditPoints)
        SearchWindow.setTabOrder(self.lineEditPoints, self.lineEditChampionship)
        SearchWindow.setTabOrder(self.lineEditChampionship, self.lineEditEntries)
        SearchWindow.setTabOrder(self.lineEditEntries, self.lineEditPodiums)
        SearchWindow.setTabOrder(self.lineEditPodiums, self.comboBoxNationality)
        SearchWindow.setTabOrder(self.comboBoxNationality, self.pushButtonSubmit)
        SearchWindow.setTabOrder(self.pushButtonSubmit, self.pushButtonReset)
        SearchWindow.setTabOrder(self.pushButtonReset, self.textEdit_8)
        SearchWindow.setTabOrder(self.textEdit_8, self.textEdit_2)
        SearchWindow.setTabOrder(self.textEdit_2, self.textEdit_7)
        SearchWindow.setTabOrder(self.textEdit_7, self.textEdit_3)
        SearchWindow.setTabOrder(self.textEdit_3, self.textEdit_6)
        SearchWindow.setTabOrder(self.textEdit_6, self.textEdit_9)
        SearchWindow.setTabOrder(self.textEdit_9, self.textEdit_10)
        SearchWindow.setTabOrder(self.textEdit_10, self.textEdit_5)
        SearchWindow.setTabOrder(self.textEdit_5, self.textEdit)

    def retranslateUi(self, SearchWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchWindow.setWindowTitle(_translate("SearchWindow", "Search"))
        self.textEdit.setHtml(_translate("SearchWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Query Database</span></p></body></html>"))
        self.pushButtonReset.setText(_translate("SearchWindow", "Reset"))
        self.pushButtonSubmit.setText(_translate("SearchWindow", "Submit"))
        self.textEdit_5.setHtml(_translate("SearchWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">Win:</span></p></body></html>"))
        self.textEdit_7.setHtml(_translate("SearchWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">Points:</span></p></body></html>"))
        self.textEdit_6.setHtml(_translate("SearchWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">Podiums:</span></p></body></html>"))
        self.textEdit_8.setHtml(_translate("SearchWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">Entries:</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("SearchWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">Name:</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("SearchWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">Team:</span></p></body></html>"))
        self.textEdit_9.setHtml(_translate("SearchWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">Championship:</span></p></body></html>"))
        self.textEdit_10.setHtml(_translate("SearchWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">Nationality:</span></p></body></html>"))
